version: '3.8'

services:
  app:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_NAME=postgres
      - DB_PORT=5432
      - REDIS_ADDR=redis:6379
      - JWT_SECRET=your_jwt_secret_key
      - PORT=3000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db-data:
